### ISSUE TITLE
I add your package to my project and I get some error when I try run project on android

### ISSUE THREAD

**Issue by alirezat66** [eademir/fading-images-slider#1]
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/alireza/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/fading_images_slider-0.0.2+2/android/local.properties'.

Exception: The plugin fading_images_slider could not be built due to the
issue above.

**Comment by eademir** [comment]
Hi @alirezat66. Can you share your `flutter doctor`'s output?
